### ISSUE TITLE
how to handle formdata with endpoints

### ISSUE THREAD

**Issue by bitdom8** [gornostay25/svelte-adapter-bun#17]
Got error: `FormData parse error missing final boundary`

```
login: async ({ cookies, request, locals }) => {   
49 |     let res;
50 |     try {
51 |       await db.use({ ns: "xx", db: "xx" });
52 |       const formData = await request.formData();     
                                 ^
TypeError: FormData parse error missing final boundary    
      at /usr/local/lsws/nodes/xx/build/server/entries/pages/_lang_/_page.server.ts.js:52:29
```

https://kit.svelte.dev/docs/form-actions

**Comment by bitdom8** [comment]
After debugging, still getting `FormData parse error missing final boundary` and it's not related to endpoints. Searched here but couldn't understand https://github.com/oven-sh/bun/issues/621

**Comment by bitdom8** [comment]
Even tried this but no success https://github.com/sveltejs/kit/pull/6901 @gornostay25

**Comment by bitdom8** [comment]
Managed dto have a different bun running outside of sveltekit then was able. Sveltekit makes things hard with cross-side. Even tried node-adaptor

**Comment by jakebottrall** [comment]
It looks like this isn't only affecting sveltekit/sveltekit-bun-adaptor, https://github.com/oven-sh/bun/issues/2644.

**Comment by Paultje52** [comment]
Recently I encountered the same issue. It started when updating from 0.5.0 to 0.5.1. I'm using bun 1.0.4 [because of another issue](https://github.com/oven-sh/bun/issues/6687).

Here is a basic project to reproduce the error. Edit the import in `svelte.config.js` to see that it's working in `0.5.0`, but not in `0.5.1`.
[svelte-adapter-bun-formdata.zip](https://github.com/gornostay25/svelte-adapter-bun/files/13628853/svelte-adapter-bun-formdata.zip)

_Note: In the example I'm using `@catdadcode/svelte-adapter-bun` because of #39_
